<style>
.menu_item {
	border:1px solid grey;
	padding:5px;
	margin-bottom:5px;
}

.delete_menu_item {
	float:right;
	cursor:pointer;
}
</style>
<div class="page-title">
	<h1><?php echo $this->__('Restaurant Menu - Add') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/save') ?>" method="post" id="form-validate-restaurant" enctype="multipart/form-data">
	<div class="fieldset">
		<?php echo $this->getBlockHtml('formkey') ?>
		<h2 class="legend"><?php echo $this->__('Restaurant Menu Information') ?></h2>
		<ul class="form-list" id='menu_item_form_fields'>
			<div class='menu_item'>
				<span class='delete_menu_item' onClick="delete_menu_item(this)">X</span>
				<li>
					<div class="field">
						<label for="stores" class="required"><em>*</em><?php echo $this->__('Item Name') ?></label>
						<div class="input-box">
							<input type='text' name='item_name[]' class='input-text required-entry' />
						</div>
					</div>
				</li>
				
				<li>
					<div class="field">
						<label for="stores" class="required"><em>*</em><?php echo $this->__('Price') ?></label>
						<div class="input-box">
							<input type='text' name='item_price[]' class='input-text required-entry' />
						</div>
					</div>			
				</li>
				
				<li>
					<div class="field">
						<label for="category" class="required"><em>*</em><?php echo $this->__('Category') ?></label>
						<div class="input-box">
							<select name='category[]' class='input-text required-entry'>
								<?php
								$customer_id = Mage::getSingleton('customer/session')->getId();
								$categorysets = Mage::getModel('restaurant/categoryset')
									->getCollection()
									->addAttributeToFilter("is_active", 1)
									->addAttributeToFilter("merchant_id", $customer_id);
								foreach($categorysets as $categoryset) {
									$categoryset = Mage::getModel('restaurant/categoryset')->load($categoryset->getEntityId());
									$active_categoryset_id = $categoryset->getEntityId();
								}
								
								$categories = Mage::getModel('restaurant/category')
									->getCollection()
									->addAttributeToFilter("merchant_id", $customer_id)
									->addAttributeToFilter("categoryset_id", $active_categoryset_id);
								foreach($categories as $category) {
									$category = Mage::getModel('restaurant/category')->load($category->getEntityId());
									?>
									<option value='<?php echo $this->__($category->getEntityId()) ?>'><?php echo $this->__($category->getName()) ?></option>
									<?php
								}
								?>
							</select>
						</div>
					</div>			
				</li>
				
				<li>
					<div class="field">
						<div class="upload-head">
							<label for="image" class="required"><?php echo $this->__('Upload Image') ?></label>
						</div>
						<div class="input-box">
							<input type="file" id="item_image" name='item_image[]' title="<?php echo $this->__('Image') ?>" class="input-text required-entry" />
						</div>
					</div>
				</li>
			</div>
		</ul>
		
		<div class="buttons-set">
			<p class="back-link">
				<a href="javascript:void(0)" id='add_new_item' onclick='add_item_fields()'>
					<?php echo $this->__('Add New Item') ?>
				</a>
			</p>
		</div>
		
		<div class="buttons-set">
			<p class="required"><?php echo $this->__('* Required Fields') ?></p>
			<p class="back-link">
				<a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" >
					<small>&laquo; </small>
					<?php echo $this->__('Back') ?>
				</a>
			</p>
			<button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
		</div>
	</div>
</form>

<script type="text/javascript">
//<![CDATA[
var productForm = new VarienForm('form-validate-restaurant', true);
//]]>
function callController(sid) {
	new Ajax.Request("<?php echo $this->getUrl('restaurant/index/gettoreategory') ?>", {
		method: 'Post',
		parameters: {'store_id':sid},
		onComplete: function(transport) {
			document.getElementById('category_html').innerHTML=transport.responseText;
			alert(transport.responseText);
			//alert(sid);
		}
	});
}

function add_item_fields() {
	var new_item_html ="<span class='delete_menu_item' onClick=\"delete_menu_item(this)\">X</span>" +
		"<li>" +
			"<div class=\"field\">" +
				"<label for=\"stores\" class=\"required\"><em>*</em>Item Name</label>" +
				"<div class=\"input-box\">" +
					"<input type='text' name='item_name[]' class='input-text required-entry' />" +
				"</div>" +
			"</div>" +
		"</li>" +
		
		"<li>" +
			"<div class=\"field\">" +
				"<label for=\"stores\" class=\"required\"><em>*</em>Price</label>" +
				"<div class=\"input-box\">" +
					"<input type='text' name='item_price[]' class='input-text required-entry' />" +
				"</div>" +
			"</div>" +
		"</li>" +
		
		"<li>" +
			"<div class=\"field\">" +
				"<label for=\"category\" class=\"required\"><em>*</em>Category</label>" +
				"<div class=\"input-box\">" +
					"<select name='category[]' class='input-text required-entry'>" +
						"<option>APPETIZERS & TAPAS</option>" +
						"<option>WOOD-FIRE SIGNATURES</option>" +
						"<option>SOUPS</option>" +
						"<option>PIZZA</option>" +
						"<option>SANDWICHES</option>" +
						"<option>PASTA</option>" +
						"<option>SEAFOOD</option>" +
						"<option>SIDES</option>" +
						"<option>DESSERTS</option>" +
						"<option>BEVERAGES</option>" +
					"</select>" +
				"</div>" +
			"</div>" +	
		"</li>" +
		
		"<li>" +
			"<div class=\"field\">" +
				"<div class=\"upload-head\">" +
					"<label for=\"image\" class=\"required\"></label>" +
				"</div>" +
				"<div class=\"input-box\">" +
					"<input type=\"file\" id=\"item_image\" name=\"item_image[]\"  title=\"Image\" class=\"input-text required-entry\" />" +
				"</div>" +
			"</div>" +
		"</li>";
	
	var div = document.createElement("div");
	div.className = "menu_item";
	div.innerHTML = new_item_html;
	document.getElementById('menu_item_form_fields').appendChild(div);
}

function delete_menu_item(node) {
	node.parentNode.remove();
}
</script>