<style>
.common-orange-button {
	background: none repeat scroll 0 0 #3399cc;
	border: 1px solid #3399cc;
	color: #fff;
	display: block;
	font: bold 12px/19px Arial,Helvetica,sans-serif;
	height: 19px;
	padding: 0 8px;
	text-align: center;
	text-decoration: none;
	white-space: nowrap;
	float: right;
	margin: 0 0 5px;
	width: auto;
}

.adverizent a:hover {
	color: #fff !important;
}
</style>
<?php $getStoreData= Mage::helper('restaurant')->getStoreData();
$getAllCategoriesDATA= Mage::helper('restaurant')->getAllCategoriesDATA();
//print_r($getAllCategoriesDATA);?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php //$collection = $this->getCollection(); ?>
<?php $collection = Mage::getModel('restaurant/item')->getCollection()->addAttributeToFilter('restaurant_menu_id', $this->getRequest()->getParam('id')); ?>

<div class="page-title adverizent">
	<h1><?php echo $this->__('Menu Items') ?></h1>
	<a href="<?php echo $this->getUrl('restaurant/item/add/menuid/'.$this->getRequest()->getParam('id')); ?>" class="common-orange-button"><?php echo $this->__('Add Item'); ?></a><div class="clear"></div>
</div>
<div style="clear:both"></div>
<?php echo $this->getToolbarHtml(); ?>
<?php if($collection->getSize()): ?>
	<table class="data-table" id="my-custom-table">
		<col width="1" />
		<col width="1" />
		<col />
		<col width="1" />
		<col width="1" />
		<col width="1" />
		<thead>
			<tr>
				<th><?php echo $this->__('ID #') ?></th>
				<th><?php echo $this->__('Name') ?></th>
				<th><?php echo $this->__('Image') ?></th>
				<th><?php echo $this->__('Description') ?></th>
				<th><?php echo $this->__('Price') ?></th>
				<th><?php echo $this->__('Category') ?></th>
				<th><span class="nobr"><?php echo $this->__('Created') ?></span></th>
				<th><span class="nobr"><?php echo $this->__('Action') ?></span></th>
			</tr>
		</thead>
		<tbody>
			<?php $_odd = '';
			$path = Mage::getBaseUrl('media') ."restaurant_menu/" ;
			?>
			<?php foreach ($collection as $_obj): ?>
				<?php $_obj = Mage::getModel('restaurant/item')->load($_obj->getEntityId())?>
				<tr>
					<td><?php echo $_obj->getEntityId() ?></td>
					<td><?php echo $_obj->getName() ?></td>
					<td><span class="nobr"><img src="<?php echo $path.$_obj->getImage(); ?>" width="120"></span></td>
					<td><?php echo $_obj->getDescription() ?></td>
					<td>
					<?php
					if($_obj->getSize() == Livetameion_Restaurant_Model_Item::SINGLE_SIZE) {
						echo "Single Size: " . $_obj->getSingleSizePrice();
					} else {
						echo "Small Size: " . $_obj->getSmallSizePrice() . "<br />";
						echo "Medium Size: " . $_obj->getMediumSizePrice() . "<br />";
						echo "Large Size: " . $_obj->getLargeSizePrice() . "<br />";
						echo "Half Size: " . $_obj->getHalfOrderPrice() . "<br />";
						echo "Full Size: " . $_obj->getFullOrderPrice() . "<br />";
						echo "Child Size: " . $_obj->getChildOrderPrice();
					}
					?>
					
					</td>
					<?php
						$category_id = $_obj->getCategoryIds();
						$category = Mage::getModel("restaurant/category")->load($category_id);
					?>
					<td><?php echo $category->getName(); ?></td>
					<td><?php echo $this->formatDate($_obj->getCreatedTime()) ?></td>
					<td>
						<a href="<?php echo $this->getUrl('restaurant/item/delete', array('id' => $_obj->getEntityId())) ?>"><?php echo $this->__('Delete') ?></a>
						/
						<a href="<?php echo $this->getUrl('restaurant/item/edit', array('id' => $_obj->getEntityId())) ?>"><?php echo $this->__('Edit') ?></a>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<script type="text/javascript">decorateTable('my-custom-table');</script>
<?php echo $this->getToolbarHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('No restaurant menus available.'); ?></p>
<?php endif ?>

