<script src="http://code.jquery.com/jquery-1.8.3.min.js"></script>
<script>
$(function(){
	$('nav#restaurant_menu_nav a').each(function() {
		if ($(this).prop('href') == window.location.href) {
			$(this).addClass('current');
		}
	});
});
</script>
<style>
nav#restaurant_menu_nav a.current {
	background:red;
	color:white;
}

nav#restaurant_menu_nav a.current {
	background:darkblue;
	color:white;
}
</style>
<nav id="restaurant_menu_nav">
<a href="<?php echo $this->getUrl('restaurant/index/index') ?>" class=""><?php echo $this->__('Menus') ?></a>
|
<a href="<?php echo $this->getUrl('restaurant/categoryset/index') ?>" class=""><?php echo $this->__('Categories') ?></a>
<br /><br />
</nav>