<style>
.common-orange-button {
	background: none repeat scroll 0 0 #3399cc;
	border: 1px solid #3399cc;
	color: #fff;
	display: block;
	font: bold 12px/19px Arial,Helvetica,sans-serif;
	height: 19px;
	padding: 0 8px;
	text-align: center;
	text-decoration: none;
	white-space: nowrap;
	float: right;
	margin: 0 0 5px;
	width: auto;
}

.adverizent a:hover {
	color: #fff !important;
}
</style>
<?php echo "header.phtml..."; ?>