<style>
.common-orange-button {
	background: none repeat scroll 0 0 #3399cc;
	border: 1px solid #3399cc;
	color: #fff;
	display: block;
	font: bold 12px/19px Arial,Helvetica,sans-serif;
	height: 19px;
	padding: 0 8px;
	text-align: center;
	text-decoration: none;
	white-space: nowrap;
	float: right;
	margin: 0 0 5px;
	width: auto;
}

.adverizent a:hover {
	color: #fff !important;
}
</style>
<?php $getStoreData= Mage::helper('restaurant')->getStoreData();
$getAllCategoriesDATA= Mage::helper('restaurant')->getAllCategoriesDATA();
//print_r($getAllCategoriesDATA);?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php //$collection = $this->getCollection(); ?>
<?php $collection = Mage::getModel('restaurant/item')->getCollection(); ?>

<div class="page-title adverizent">
	<h1><?php echo $this->__('Menu Items') ?></h1>
	<a href="<?php echo $this->getUrl('restaurant/index/add') ?>" class="common-orange-button"><?php echo $this->__('Add Item') ?></a><div class="clear"></div>
</div>
<div style="clear:both"></div>
<?php echo $this->getToolbarHtml(); ?>
<?php if($collection->getSize()): ?>
	<table class="data-table" id="my-custom-table">
		<col width="1" />
		<col width="1" />
		<col />
		<col width="1" />
		<col width="1" />
		<col width="1" />
		<thead>
			<tr>
				<th><?php echo $this->__('ID #') ?></th>
				<th><?php echo $this->__('Store Name') ?></th>
				<th><?php echo $this->__('Category') ?></th>
				<th><?php echo $this->__('Preview') ?></th>
				<th><span class="nobr"><?php echo $this->__('Status') ?></span></th>
				<th><span class="nobr"><?php echo $this->__('Created') ?></span></th>
				<th><span class="nobr"><?php echo $this->__('Page Location') ?></span></th>
				<th><span class="nobr"><?php echo $this->__('Action') ?></span></th>
			</tr>
		</thead>
		<tbody>
			<?php $_odd = '';
			$path = Mage::getBaseUrl('media') ."restaurant_menu/" ;
			 ?>
			<?php foreach ($collection as $_obj): ?>
				<tr>
					<td><?php echo $_obj->getItemId() ?></td>
					<td> <?php echo $getStoreData[$_obj->getStore_id()]; ?></td>
					<td><span class="nobr"><?php 
					$catID=@explode(',', $_obj->getCategories());
					foreach($catID as $val) {
						echo $getAllCategoriesDATA[$val];echo '<br/>';
					}
					
					// echo $_obj->getCategories(); ?></span></td>
					<td><span class="nobr"><img src="<?php echo $path.$_obj->getItemImage(); ?>" width="120"></span></td>
					<td><?php $status= $_obj->getActive_status();
					if($status==1) {
						?>
						<a href="<?php echo $this->getUrl('restaurant/index/status', array('id' => $_obj->getItemId(),'status' => 'in-active')) ?>"><?php echo $this->__('Active') ?></a>
						<?php
					} else {
						?>
						<a href="<?php echo $this->getUrl('restaurant/index/status', array('id' => $_obj->getItemId(),'status' => 'active')) ?>"><?php echo $this->__('In-active') ?></a>
						<?php
					}
					?>
					</td>
					<td><?php echo $this->formatDate($_obj->getCreatedTime()) ?></td>
					<td><?php echo $_obj->getPage_location() ?></td>
					<td>
						<a href="<?php echo $this->getUrl('restaurant/index/delete', array('id' => $_obj->getItemId())) ?>"><?php echo $this->__('Delete') ?></a>
						<a href="<?php echo $this->getUrl('restaurant/index/edit', array('id' => $_obj->getItemId())) ?>"><?php echo $this->__(' / Edit') ?></a>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<script type="text/javascript">decorateTable('my-custom-table');</script>
<?php echo $this->getToolbarHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('No restaurant menus available.'); ?></p>
<?php endif ?>

