<style>
.common-orange-button {
	background: none repeat scroll 0 0 #3399cc;
	border: 1px solid #3399cc;
	color: #fff;
	display: block;
	font: bold 12px/19px Arial,Helvetica,sans-serif;
	height: 19px;
	padding: 0 8px;
	text-align: center;
	text-decoration: none;
	white-space: nowrap;
	float: right;
	margin: 0 0 5px;
	width: auto;
}

.adverizent a:hover {
	color: #fff !important;
}
</style>
<?php

//echo "<pre>";
$menu_id = $this->getRequest()->getParam("id");
if(isset($menu_id) && !empty($menu_id)) {
	/*
	$items = Mage::helper('restaurant')->getMenuItemsFor($menu_id);
	foreach($items as $item) {
		//print_r($item->getData());
	}
	*/
	?>
	<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
		<html xmlns="http://www.w3.org/1999/xhtml">
		
	<!-- Mirrored from www.onlineorderingdemo.com/freshlocalbistro by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 14 Apr 2015 12:01:26 GMT -->
	<head>
		<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
		<meta http-equiv="X-UA-Compatible" content="IE=11; IE=10; IE=9; IE=8; IE=EDGE" />
		<!--Below allows access to cross-domain cookies in IE to fix iFrame modifier-modifier issue-->
			
			<title>
				Fresh Local Bistro Online Ordering		</title>
		<link id="favicon" rel="shortcut icon" href="favicons/empty.png" />	<meta name="keywords" content="online menu ordering, online ordering, restaurants, restaurant online ordering, online ordering for restaurants, online ordering software, online ordering solutions, online orders, restaurant ordering, online takeout, restaurant internet ordering, restaurant web ordering, online ordering system, online food ordering system, restaurant online ordering system, pizza online ordering system, online pizza ordering system, online menu, food ordering">
			
			<meta property="og:title" content="Fresh Local Bistro"/>
			<meta property="og:type" content="restaurant"/>
			<meta property="og:image" content="admin/banner/1412376837.png"/>
			<meta property="og:site_name" content="Fresh Local Bistro Online Ordering"/>
			<meta property="og:description" content="Our team at Fresh Local Bistro are committed to providing comfort food in a comfortable environment. All of our ingredients are grown locally and we offer a broad assortment of fair trade products from around the world. Support your local economy and stop by today!
	"/>
			<meta property="og:latitude" content="40.208016"/>
			<meta property="og:longitude" content="-77.200267"/>
			<meta property="og:street-address" content="453 Lincoln St"/>
			<meta property="og:locality" content="Carlisle"/>
			<meta property="og:region" content="Pennsylvania"/>
			<meta property="og:postal-code" content="17013"/>
			<meta property="og:country-name" content="USA"/>
		
		
				<!-- added by Kryz for toggling online ordering -->
				<!-- Link to the stylesheet -->
				<link rel="stylesheet" type="text/css" href="css/ui-lightness/jquery-ui-1.8.10.custom.css" />
		
				<!-- Includes javascripts -->
				<script type="text/javascript" src="../w.sharethis.com/button/buttons.js"></script>
				<script type="text/javascript">stLight.options({publisher:'4ae1f2bf-9e4d-47f1-815c-b7fb9a77d51d', headerTitle:'Share Our Menu with Friends', headerfg:'#000000'});</script>
				<script type="text/javaScript" src="javascript/jquery-1.4.4.min.js"></script>
				<script type="text/javaScript" src="javascript/jquery-ui-1.8.10.custom.min.js"></script>
		
				<script type='text/javaScript'>var restaurantID = 385</script><script type='text/javaScript'>var inFacebook = 0</script><script type='text/javaScript'>var locationId = 359</script>			<script type="text/javaScript" src="javascript/restaurant_home470a.js?version=022015"></script>
				<script type="text/javascript" src="admin/geofence_files/ibox.2.2/ibox.js"></script>
				<script type="text/javaScript" src="javascript/modifierfeature470a.js?version=022015"></script>
				<script type="text/javaScript" src="javascript/cookie.js"></script>
				<script type="text/javascript" src="javascript/jquery.tipTip.js"></script>
				<script type="text/javascript" src="javascript/jquery.tipTip.minified.js"></script>
				<script type="text/javascript">
					$(function(){
					$(".tTip").tipTip();
					});
				</script>
				
		<script type="text/javascript">
		
		$(function()
		{
			var timestamp = new Date;
			var day = timestamp.getDay();
			
			if( day == 0 )
			{
				day = 'SUNDAY';
				//$("#SUNDAY").css( "background-color","#fff9d7" );
			}
			if( day == 1 )
			{
				day = 'MONDAY';
				//$("#MONDAY").css( "background-color","#fff9d7" );
			}
			if( day == 2 )
			{
				day = 'TUESDAY';
				//$("#TUESDAY").css( "background-color","#fff9d7" );
			}
			if( day == 3 )
			{
				day = 'WEDNESDAY';
				//$("#WEDNESDAY").css( "background-color","#fff9d7" );
			}
			if( day == 4 )
			{
				day = 'THURSDAY';
				//$("#THURSDAY").css( "background-color","#fff9d7" );
			}
			if( day == 5 )
			{
				day = 'FRIDAY';
				//$("#FRIDAY").css( "background-color","#fff9d7" );
			}
			if( day == 6 )
			{
				day = 'SATURDAY';
				//$("#SATURDAY").css( "background-color","#fff9d7" );
			}
		});
		var current_item_id = 0;
		
		var openDivId=null;
		
		var level = 0;
		var categoryid=0;
		var indexid='none';
		var modifier_grp_item_id = new Array();
		var topping_group_id_arr = new Array();
		
		</script>
		<script type="text/JavaScript" src="scripts/menu.js"></script>
		<!-- <script type="text/javascript" src="scripts/jquery.js"></script>	-->
		<script type="text/javascript" src="javascript/modal470a.js?version=022015"></script>
		<script type="text/javascript" src="javascript/group_order470a.js?version=022015"></script>	
		<link href="css/global.css" rel="stylesheet" type="text/css" />
	<style type="text/css">
	body 
	{
		margin-left: 0px;
		margin-top: 0px;
		margin-right: 0px;
		margin-bottom: 0px;
		
		background-color:#f2efd9 ;

		font-family:Arial, Verdana, Helvetica, Geneva, Trebuchet MS, sans-serif;
				background-image: url(background_images/359.jpg);
			
	}


	/* Link color */
	a
	{
		color:#25771b;
		text-decoration:none;
	}

	a:hover
	{
		color:#EB7228;
		text-decoration:none;
	}

	/* Menu Link Color */
	#sublinksmenu A:hover 
	{
		COLOR: #EB7228; 
		TEXT-DECORATION: none;
	}
	#sublinksmenu 
	{
		color: #25771b;
		font-size:11px;	
	}
	#sublinksmenu A {
		color: #25771b;
		TEXT-DECORATION: none;
		font-weight:bold;
		font-size:11px;	
	}

	/* Sideboxes color */
	.bg_lightblue {
		background-color:#ffffff;
		
	}

	.border_bottom3 
	{
		height: 32px;
		line-height: 32px;

		background-color: #ffffff;
		padding-left: 8px;
		
		
	}

	/* Topbars  */
	.cu_side_heading
	{
		background-color:#663300;
		background-image:url('css/cosmetics/dual_layered_masks_1x36.png');

		height: 36px;
		line-height: 36px;

		color:#ffffff;
		font-weight:bold;
		font-size:14px;
		font-family: Arial, Helvetica, sans-serif;
		-moz-border-radius: 5px 5px 0px 0px;
		-webkit-border-radius: 5px 5px 0px 0px;
		border-radius: 5px 5px 0px 0px;

	}

	/* Top Bar for some pages */
	.cu_inner_heading 
	{
		background-image:url('css/cosmetics/standard_layer_mask_1x26.png');
		height:26px;
		line-height:26px;
		background-repeat: repeat-x;

		border-top-width: 1px;
		border-right-width: 1px;
		border-bottom-width: 1px;
		border-left-width: 1px;
		/* border-top-style: solid; */
		/* border-right-style: solid; */
		/* border-bottom-style: solid; */
		/* border-left-style: solid; */
		border-top-color: #663300;
		border-right-color: #663300;
		border-bottom-color: #663300;
		border-left-color:#663300;
		background-color: #663300;
		padding-left: 8px;
		/*Text Color*/
		color:#ffffff;
		font-weight: bold;
		-moz-border-radius: 5px 5px 5px 5px; 
		-webkit-border-radius: 5px 5px 5px 5px;
		border-radius: 5px 5px 5px 5px;
		//behavior: url('library/PIE/PIE.php');
		
	}


	.cu_main_heading
	{
		background-image:url('css/cosmetics/main_center_header_layer_mask_1x38.png');
		height:38px;
		line-height:38px;
		background-repeat: repeat-x;
		color:#ffffff;
		background-color:#663300;
		border: 1px solid #663300;
		-moz-border-radius: 5px 5px 5px 5px; 
		-webkit-border-radius: : 5px 5px 5px 5px;
		border-radius: 5px 5px 5px 5px;

	}

	/* Sidebar Border Color */
	.border_bottom2 
	{
		//background-image:url('http://cosmetic.localhost/css/cosmetics/standard_layer_mask_1x26.png');
		background-image:url('css/cosmetics/standard_layer_mask_1x26.png');
		//background-image:url('../css/cosmetics/standard_layer_mask_1x26.png');
		height:26px;
		line-height:26px;
		background-repeat: repeat-x;

		/*Text Color*/
		color:#ffffff;

		border-top-width: 1px;
		border-right-width: 1px;
		border-bottom-width: 1px;
		border-left-width: 1px;
		/* border-top-style: solid; */
		/* border-right-style: solid; */
		/* border-bottom-style: solid; */
		/* border-left-style: solid; */

		border-top-color: #663300;
		border-right-color: #663300;
		border-bottom-color: #663300;
		border-left-color:#663300;
		background-color: #663300;

		padding-left: 8px;
		font-weight: bold;
		-moz-border-radius: 5px 5px 5px 5px; 
		-webkit-border-radius: : 5px 5px 5px 5px;
		border-radius: 5px 5px 5px 5px;
		
	}

	/* Button Color*/
	/*
	.button 
	{ 
	   color:#FFFFFF;
	   height: 22px;
	   font-weight:bold;
	   background-color:#25771b;
	   border:1px solid;
	   border-top-color:#00009B;
	   border-left-color:#00009B;
	   border-right-color:#00009B;
	   border-bottom-color:#00009B;

		filter:progid:DXImageTransform.Microsoft.Gradient
		  (GradientType=0,StartColorStr='#778DC4',EndColorStr='#25771b');
	}

	*/
	.button_view 
	{ 
	   color:#FFFFFF;
	   height: 22px;
	   font-weight:bold;
	   background-color:#25771b;
	   border:1px solid;
	   border-top-color:#00009B;
	   border-left-color:#00009B;
	   border-right-color:#00009B;
	   border-bottom-color:#00009B;

		filter:progid:DXImageTransform.Microsoft.Gradient
		  (GradientType=0,StartColorStr='#778DC4',EndColorStr='#663300');
	}

	input.buttonhov
	{
	   border-top-color:#EB7228;
	   border-left-color:#EB7228;
	   border-right-color:#930;
	   border-bottom-color:#930;
	} 

	/*Text Color*/
		
	/* Menu Text Color*/
	.txt_orange2 
	{
		color: #25771b;
		//color: #434343;
		font-weight: bold;
		font-size:13px;
	}
	/* Menu Text Color*/
	.txt_menu_items
	{
		color: #25771b;
		font-weight: bold;
		font-size:12px;
	}

		/* Right Cart Text Color*/
	.txt_orange 
	{
		color: #25771b;
		font-weight: bold;
	}
	/*
	.txt_cart
	{
		color: #25771b;
	}
	*/
	.cart_fill_1
	{
		background-color: #363636;
	}
	.cart_fill_2
	{
		background-color: #ffffff;

	}
	.cart_border_right
	{
		border-right-style: solid;
		border-right-width: 1px;
		border-right-color: #363636;
	}
	.cart_border_left
	{
		border-left-style: solid;
		border-left-width: 1px;
		border-left-color: #363636;
	}
	.cart_border_top
	{
		/* border-top-style: solid; */
		border-top-width: 1px;
		border-top-color: #363636;
	}
	.cart_border_bottom
	{
		border-bottom-style: solid;
		border-bottom-width: 1px;
		border-bottom-color: #363636;
	}
	.cart_text_1
	{
		color: #ffffff;
	}
	.cart_text_2
	{
		color: #363636;
	}
	.cart_text_3
	{
		color: #363636;
	}

	/*Address Text Color*/
	.general_text
	{
		color: #25771b;
	}

	.txt_h1 
	{
		font-size: 16px;
		font-weight: bolder;
		color: #25771b;
	}
	.txt_blue
	{
		color:#25771b;
	}

	.float_left
	{
		float: left;
	}
	.float_right
	{
		float: right;
	}
	.icon_large
	{
		margin: 3px;
		height: 32px;
		width: 32px;
		background-repeat:no-repeat;
		background-position:center;
	}
	.pad{ background-image:url('css/images/icons/pad.png');}
	.map{ background-image:url('css/images/icons/map.png');}
	.arrow{ background-image:url('css/images/icons/arrow.png');}
	.email{ background-image:url('css/images/icons/email.png');}
	.print{ background-image:url('css/images/icons/print.png');}
	.sharethis{ background-image:url('css/images/icons/sharethis.png');}
	.cart{ background-image:url('css/images/icons/cart.png');}
	.plate{ background-image:url('css/images/icons/plate.png');}
	.terms{ background-image:url('css/images/icons/terms.png');}
	.padlock{ background-image:url('css/images/icons/padlock.png');}
	.cart_arrow{ background-image:url('css/images/icons/cart_arrow.png');}
	.edit{ background-image:url('css/images/icons/edit.png');}
	.review{ background-image:url('css/images/icons/review.png');}
	.home{ background-image:url('css/images/icons/home.png');}
	.mouse{ background-image:url('css/images/icons/mouse.png');}
	.terms{ background-image:url('css/images/icons/terms.png');}
	.padlock{ background-image:url('css/images/icons/padlock.png');}
	.reward{ background-image:url('css/images/icons/reward.png');}
	.payment{ background-image:url('css/images/icons/payment.png');}

	.icon_small
	{
		margin: 5px;
		height: 16px;
		width: 16px;
		background-repeat:no-repeat;
		background-position:center;
	}
	.info{ background-image:url('css/images/icons/info.png');}
	.user{ background-image:url('css/images/icons/user.png');}
	.clock{ background-image:url('css/images/icons/clock.png');}
	.money{ background-image:url('css/images/icons/money.png');}
	.scissors{ background-image:url('css/images/icons/scissors.png'); margin:4px;}
	.camera{ background-image:url('css/images/icons/camera.png');}
	.document{ background-image:url('css/images/icons/document.png');}
	.gratuity{ background-image:url('css/images/icons/gratuity.png');}
	.ribbon{ background-image:url('css/images/icons/ribbon.png');}
	.lock{ background-image:url('css/images/icons/lock.png');}
	.cart2{ background-image:url('css/images/icons/cart2.png');}
	.grouporder{ background-image:url('css/images/icons/grouporder.png');}

	.ui-corner-all
	{ 
		-moz-border-radius: 5px 5px 5px 5px; 
		-webkit-border-radius: : 5px 5px 5px 5px;
		border-radius: 5px 5px 5px 5px;
	}
	.submenu_layer_mask
	{
		background-image:url('css/cosmetics/submenu_layer_mask_1px.png');

	}
	.highlight
	{
		background-color: #66b711;
	}
	.highlight a
	{
		color: #ffffff;
	}
	.selected
	{
		background-color: #66b711;
	}
	.selected a
	{
		color: #ffffff;
	}

	.cart_side_heading
	{
		text-align: center;
		color:#ffffff;
		height:34px; line-height:34px;
		padding: 6px;
		/* border: 1px solid #363636; */
		background-color: #363636;
		background-image:url('css/cosmetics/standard_layer_mask_1x36.png');
		background-position:top left;
		background-repeat: repeat-x;
		-moz-border-radius: 5px 5px 0px 0px; 
		-webkit-border-radius: 5px 5px 0px 0px;  
		border-radius: 5px 5px 0px 0px; 
		color:#FFFFFF;
		font-size:14px;
		font-family: Arial, Helvetica, sans-serif
	}

	.cart_bottom
	{
		/* border: 1px solid #363636; */
		background-color: #363636;
		-moz-border-radius: 0px 0px 5px 5px; 
		-webkit-border-radius: 0px 0px 5px 5px;  
		border-radius: 0px 0px 5px 5px;

	}
	.odd
	{
		background-color: #f2f2f2;
	}

	.button_proper 
	{
		/*
		-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
		-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
		box-shadow:inset 0px 1px 0px 0px #ffffff;
		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #25771b), color-stop(1, #25771b) );
		background:-moz-linear-gradient( center top, #25771b 5%, #25771b 100% );
		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#25771b', endColorstr='#25771b');
		*/
		background-color:#25771b;
		-moz-border-radius: 5px;
		-webkit-border-radius: 5px;
		border-radius: 5px;
		border:1px solid #25771b;
		display:inline-block;
		color:#ffffff;
		font-family:arial;
		font-size:13px;
		font-weight:bold;
		padding:6px 8px;
		text-decoration:none;
	}
	/*
	.button_proper:hover {
		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #25771b), color-stop(1, #25771b) );
		background:-moz-linear-gradient( center top, #25771b 5%, #25771b 100% );
		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#25771b', endColorstr='#25771b');
		background-color:echo $cu_button;?>;
	}
	.button_proper:active {
		position:relative;
		top:1px;
	}
	*/

	.button_cancel
	{
		/*
		-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
		-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
		box-shadow:inset 0px 1px 0px 0px #ffffff;
		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );
		background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );
		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf');
		*/
		background-color:#ededed;
		-moz-border-radius: 5px;
		-webkit-border-radius: 5px;
		border-radius: 5px;
		border:1px solid #dcdcdc;
		display:inline-block;
		color:#777777;
		font-family:arial;
		font-size:13px;
		font-weight:bold;
		padding:6px 8px;
		text-decoration:none;
		//text-shadow:1px 1px 0px #ffffff;
	}

	/*
	.button_proper:active 
	{
		position:relative;
		top:1px;
	}
	*/
	.button_proper_delete
	{
		font-family:Sans-serif;
		font-size: 12px;
		color: #ffffff;
		display: inline;
		//font-weight: bold;
		text-align: left;
		position: relative;
		height: 30px;
		padding: 7px;
		border: 2px solid white;
		-moz-border-radius: 20px; 
		-webkit-border-radius: 20px; 
		border-radius: 20px;
		
		-moz-box-shadow: 1px 1px 10px rgba(10, 10, 10, 0.4);
		-webkit-box-shadow: 1px 1px 10px rgba(10, 10, 10, 0.4);
		box-shadow: 2px 2px 10px rgba(10, 10, 10, 0.4);
		-o-background: linear-gradient(top, #e28684, #c70000);
		background: -moz-linear-gradient(top, #e28684, #c70000);
		background: -webkit-gradient(linear, center top, center bottom, from(#e28684), to(#c70000));
		//-pie-background: linear-gradient(90deg, #ff9c00, #ffd71c); /*PIE*/
		filter:progid:DXImageTransform.Microsoft.Gradient(GradientType=0,StartColorStr='#ffd71c',EndColorStr='#ff9c00');
		//behavior: url('library/PIE/PIE.php');
	}


	.border_bottom_body
	{	
		
		height: 3em;
		background-color: #ffffff;
		-webkit-border-radius: 0em 0em 1em 1em;
		-moz-border-radius: 0em 0em 1em 1em;
		border-radius: 0em 0em 1em 1em;
	}
	.border_top_body
	{	
		height: 1em;
		background-color: #ffffff;
		-webkit-border-radius: 1em 1em 0em 0em;
		-moz-border-radius: 1em 1em 0em 0em;
		border-radius: 1em 1em 0em 0em;
	}

	a.buttonicon{
		background:url(css/images/button.gif);
		display:block;
		color:$cu_link;
		font-weight:bold;
		height:30px;
		line-height:29px;
		margin-bottom:4px;
		text-decoration:none;
		width:191px;
	}
	a:hover.buttonicon
	{
		color:#0066CC;
	}
	.question{
		background:url(css/images/question.png) no-repeat 6px 5px;
		text-indent:30px;
		display:block;
	}
	.stored_address{
		background:url(css/images/stored_address.png) no-repeat 6px 5px;
		text-indent:25px;
		display:block;
	}
	.stored_card{
		background:url(css/images/stored_card.png) no-repeat 6px 5px;
		text-indent:40px;
		display:block;
	}

	.cart_fill_3
	{
		background-color: #ffffff;
		border: 1px solid #a8a8a8;
	}

	.view_cart_header
	{
		text-align: left;
		color:#ffffff;
		height:34px; line-height:34px;
		padding: 6px;
		border: 1px solid #363636;
		background-color: #363636;
		background-image:url('css/cosmetics/standard_layer_mask_1x36.png');
		background-position:top left;
		background-repeat: repeat-x;
		-moz-border-radius: 5px 5px 5px 5px; 
		-webkit-border-radius: 5px 5px 5px 5px;
		border-radius: 5px 5px 5px 5px;
			
		color:#FFFFFF;
		font-size:14px;
		font-family: Arial, Helvetica, sans-serif;
	}

	.hover_menu_category
	{
		background-image:url('css/cosmetics/dual_layered_masks_1x36.png');
		background-position:top left;
		background-repeat: repeat-x;

	}


	.ui-widget-header 
	{ 
		border: 1px solid #663300; 
		background: #663300 url(css/cosmetics/main_center_header_layer_mask_1x38.png) 50% 50% repeat-x; 
		color: #ffffff; 
		font-weight: bold; 
	}


	/*Add Item button(new) css*/

	.myButton 
	{
		/*-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
		-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
		box-shadow:inset 0px 1px 0px 0px #ffffff;
		*/
		/*
		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #25771b), color-stop(1, #25771b) );
		background:-moz-linear-gradient( center top, #25771b 5%, #25771b 100% );
		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#25771b', endColorstr='#25771b');
		*/
		background-color:#25771b;
		-moz-border-radius: 5px;
		-webkit-border-radius:5px;
		border-radius: 5px;
		border:1px solid #25771b;
		display:inline-block;
		color:#ffffff;
		font-family: arial;
		font-size: 14px;
		font-weight: bold;
		padding: 2px 5px;
		text-decoration: none;
		cursor:pointer;

	}
	/*
	.myButton:hover 
	{
		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #25771b), color-stop(1, #25771b) );
		background:-moz-linear-gradient( center top, #25771b 5%, #25771b 100% );
		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#25771b', endColorstr='#25771b');
		background-color:echo $cu_button;?>;
	}
	.myButton:active {
		position:relative;
		top:1px;
	}
	*/
	.footer
	{
		/* border-top-style: solid; */
		border-top-width: 2px; 
		border-color: #d9d9d9;
	}

	.menu_nagivation_header
	{
		border-bottom-width: 3px; 
		border-bottom-style: groove;
	}

	.menu_nagivation_rows
	{
		border-bottom-width: 1px; 
		border-bottom-style: solid; 
		border-color: #b5b7b4;
	}
	.menu_item_name
	{
		font-weight: bolder; 
		font-size:15px;
	}
	.menu_item_size
	{
		position:relative; 
		left:10px;
		z-index:1; 
		font-size: 10px; 
		font-style:italic; 
		display:inline-block; 

	}
	.ui-widget-content 
	{ 
		border: 1px solid #dddddd; 
		background: #ffffff 50% top repeat-x; 
		color: #333333; 
	}
	.highlight_row
	{
		background-color: #8dbdd8;
	}

	.button_small
	{	
		display: inline-block;
		font-family: sans-serif;
		color: #ffffff;
		font-size: 14px;
		text-align: center;
		width: 25px;
		height: 25px;
		line-height: 25px;
		border-radius: 15px;
		-moz-border-radius: 15px; /* Firefox 3.6 and earlier */
		//box-shadow: 1px 1px 1px #959595;
		border-style: none;
		
	}

	.yellow
	{
		width:85px;
		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #25771b), color-stop(1, #25771b) );
		background:-moz-linear-gradient( center top, #25771b 5%, #25771b 100% );
		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#25771b, endColorstr=#25771b);
		background-color: #25771b;
	}

	.grey
	{
		width:70px;
		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #878686), color-stop(1, #555555) );
		background:-moz-linear-gradient( center top, #878686 5%, #555555 100% );
		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#878686', endColorstr='#555555');
		background-color: #555555;
	}

	.body_outline
	{
		width: 988px;
	}

	.right_column
	{
		padding-top:30px;
	}
	</style><style>.footer 
	{
		background: transparent;
		background-repeat:no-repeat;
		position: relative !important;
		width: 988px;
		height: 150px;
		margin: 0 auto;
	}

	.quick 
	{
		text-align: right;
		color: #4c290f;
		font-family: arial !important;
		width: 988px;
		margin-right: 0px;
		margin-top: 100px;
		margin-left: 0px;
	}

	.quick a 
	{
		font-size:24px !important;
		font-family: arial !important;
		color: #4c290f;
	}

	.quick a:hover 
	{
		text-decoration:underline;
		color:#25771b;
	}

	.footer_left 
	{
		color: #FFF;
	}

	.copyright
	{
		text-align: center;
		font-size: 21px;
		color: #fff200;
		font-family: arial !important;
		width: 1000px;

	}
	table.inner_body
	{
	background-color: rgba(255, 255, 255, .75);
	}
	div.border_top_body
	{
	visibility:hidden;
	}

	table.menugrouptd
	{
	background color: rgba(255,255,255,.75)
	}

	.general_text
	{
		color: #4c290f;
	}

	.border_bottom3
	{
		background: transparent;
		text-transform: uppercase;
		font-weight: bold;
	}

	.cu_side_heading
	{
		background: #4c290f;;
		color: #FFFFFF;
		text-transform: uppercase;
		font-weight: bold;
	}

	.cart_text_2
	{
		color: #4c290f;
	}

	.cart_text_3
	{
		color: #4c290f;
	}
	.odd
	{
		background-color: none;
		background: transparent;
	}

	.border_bottom_body
	{
		background: transparent;
	}
	</style>	</head>
		<body>
				 </td>
			 </tr>
		  </tbody></table>
	</div>	<!--We will read the hash anchor and set the order method type accordingly.-->
		<script type="text/javascript">
		$(function()
		{
			if( window.location.hash == "#takeout" || window.location.hash == "#curbside" || window.location.hash == "#dinein" || window.location.hash == "#delivery" )
			{
				var order_type = window.location.hash;
				order_type = order_type.replace("#","");
				$.ajax({
					url: 'set_order_type.php?order_type='+order_type,
					type: 'GET',
					dataType: 'json',
					success: function(data)
					{
						 setCookie(locationId+'_order_type', 'set');
						$("#change_order_type_cart").html('<a class="cart_text_1"  onclick="showOrderType(0)" href="javascript:void(0)">'+data+' (Change)</a>');
					}
				});
			}
			else
			{
				var setAnchors = document.URL;		
				$.ajax(
				{
					url: "set_anchors.php",
					type: "POST",
					dataType: 'json',
					data: 
					{ 
						setAnchors : setAnchors
					},
					success:function(data)
					{
						var remote_host = 'http://' + window.location.hostname;
						
						if( data != null )
						{
							//alert( data['control_character'] );
							
							if( data['control_character'] != 'item' )
							{	
								window.location.href=remote_host+'/'+data['restaurant_url'];
							}
							else if(data['control_character'] == 'item')
							{
								reset_level(); 
								create_categoryid_on_add( data['category'] ); 
								get_pro_details( data['item'], data['category'], data['item_name'], "left" ); 
								openthickbox( data['item'], data['item_name'] );
							}
							else if(data['control_character'] == 'exit')
							{
								window.location.href=remote_host+'/'+data['restaurant_url'];
							}
						}
					}
				});
			}
			
		});
		</script>

			
		<div id="menuitem_details" style="display:none"></div>
		<div id="group_order_popup" style="display:none"></div>
		<div id="signuppopup" class="signuppopupclass" style="display:none;"></div>
		
		<table border="0" align="center" cellpadding="0" cellspacing="0" class="body_outline">
			<tr>
				<td align="center" valign="bottom">
					<script type="text/JavaScript">
	var day_open="";
	</script>

	<script type="text/JavaScript">

	</script>
	<script Language="JavaScript" src="admin/includes/popcalendar.js"></script>

	  

				</td>
			</tr>
		  <tr>
			<td align="center">
			
			<table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF" class="inner_body">
				<tr>
								<td width="180" align="center" valign="top" style="padding-left:10px;">
					<script src="scripts/genMove.js" type="text/javascript"></script>
	<script src="javascript/menu.js" type="text/javascript"></script>

	<script type="text/JavaScript">
	jQuery(document).ready(function()
	{	
		
		initializeMenus();
		
		$('#menugroup').change(function()
		{
			
			menugroupid = $("#menugroup").val();
			
			$("#menugrouptd").slideUp("slow",function(){
				$.ajax({
				url: "includes/get_menugroup.php?id="+menugroupid, 
				type: 'GET',
				success: function(data) 
				{
					  document.getElementById("menugrouptd").innerHTML = data;
					 $("#menugrouptd").slideDown("slow");
					 initializeMenus();
				}
			});
			});
			
			
		});
		
		
		
		
	});


	function initializeMenus()
	{


		$('.submenu_layer_mask').hover( 
		function() 
		{
			$(this).addClass("hover_menu_category");
			$(this).css('cursor','pointer');
		}, 
		function() 
		{
			$(this).removeClass("hover_menu_category");
			$(this).css('cursor','auto');
		});
		// Initializes proper icons at time run time
		$.each( $('.submenu_layer_mask'), function()
		{
			if($(this).find('span').hasClass("contracted"))
			{
				$(this).parent().nextUntil('.menu_category').hide();
				$(this).find('span:first').removeClass('icon_expanded');
				$(this).find('span:first').addClass('icon_contracted');
			}
			
			if($(this).find('span').hasClass("expanded"))
			{
				$(this).parent().nextUntil('.menu_category').show();
				$(this).find('span:first').removeClass('icon_contracted');
				$(this).find('span:first').addClass('icon_expanded');
			}
			
		});
		
		
		// This function will get the id and current class for the clicked item to update session information for that class and id/
		$('.submenu_layer_mask').click(function()
		{
			$(this).parent().nextUntil('.menu_category').toggle();		// For whichever menu category we click, lets toggle the menu category items.

			var id = $(this).attr('rel');								// grabs the integer id of the currently clicked item
			var class_type = '';										// initialize variable
			
			if($(this).find('span:first').hasClass("contracted"))		// if the menu category is contracted/closed
			{
				class_type = 'expanded';								// intention to change/toggle class
				$(this).find('span:first').removeClass('contracted');	// change the classes within the document
				$(this).find('span:first').addClass('expanded');
				$(this).find('span:first').removeClass('icon_contracted');
				$(this).find('span:first').addClass('icon_expanded');
			}
			else													 	// if the menu category is expanded/open
			{
				class_type = 'contracted';								// intention to change/toggle class
				$(this).find('span:first').removeClass('expanded');		// change the classes within the document
				$(this).find('span:first').addClass('contracted');
				$(this).find('span:first').removeClass('icon_expanded');
				$(this).find('span:first').addClass('icon_contracted');
			}
			//alert('class_type: ' + class_type);

			$.ajax({
				url: "includes/menu_session.php?id="+id+"&class="+class_type, // request sent to update the $_SESSION to display proper class through application
				type: 'GET',
				dataType: 'json',
				success: function(data) 
				{
					//alert(data['id'] + ' ' + data['class']);
				}
			});
		});


	}

		
	function alert_msg()
	{	
		alert('This restaurant is either closed or does not have enough prep time for your order');
		return false;
	}	
	</script>
	<style type="text/css">
	.top_content_div_left_w
	{
		/*padding:0px 10px 10px 12px;*/
		float:left;
		/*width:225px;*/
		word-wrap:break-word;
		line-height:15px;
	}
	.thumb_img
	{
		float:left;
		margin-right:15px;

	}
	img 
	{ 
		/* removes border around images in firefox */
		border:none;
	}
	.icon_expanded
	{
		margin-left:5px;
		width:16px;
		height:28px;
		line-height:28px;
		background-image: url('images/bullet_toggle_minus.png');
		background-repeat:no-repeat;
		background-position:center;
	}
	.icon_contracted
	{
		margin-left:5px;
		width:16px;
		height:28px;
		line-height:28px;
		background-image: url('images/bullet_toggle_plus.png');
		background-repeat:no-repeat;
		background-position:center;
	}
	.expanded
	{

	}
	.contracted
	{

	}
	</style>
			  
			  <table width="230" border="0" align="center" cellpadding="0" cellspacing="0" id="menu">
		  
			  <tr>
				<td align="left" height="21" class="cu_side_heading border_bottom3">
					&nbsp;			
					View our Menu            		
				  
						  </td>
			  </tr>
		   
			  <tr>
				<td align="center">
					<div id="menugrouptd">    
					<table id="sublinksmenu" width="100%" border="0" cellspacing="0" cellpadding="2">
									<tr class="menu_category" >
							<td align="left" class="border_bottom3 submenu_layer_mask menu_nagivation_header" rel="0">
								<span class="expanded" style="display:inline-block; width:16px; height:16px; line-height:16px;">&nbsp;&nbsp;&nbsp;&nbsp;</span>
								<strong>
									<span class="txt_orange2"><font size="3px">MAIN MENU</font></span>
								</strong>
							</td>
						</tr>
						 
									<tr>
										<td align="left" class="border_bottom3 menu_nagivation_rows">
											<table width="100%">
												<tr>
													<td valign="middle" width="25%">
														<a href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'APPETIZERS & TAPAS')) ?>">
															<img src="https://www.onlineorderingdemo.com/category_images/3845.png" width="70" height="70" align="absmiddle" />
														</a>
													</td>
													
													<td valign="middle" width="75%" style="line-height:15px;">
														<a style="font-size:1em;" href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'APPETIZERS & TAPAS')) ?>">APPETIZERS & TAPAS</a>
													</td>
												</tr>
											</table>
										</td>
									</tr>
									
									<tr>
										<td align="left" class="border_bottom3 menu_nagivation_rows">
											<table width="100%">
												<tr>
													<td valign="middle" width="25%">
														<a href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'WOOD-FIRE SIGNATURES')) ?>">
															<img src="https://www.onlineorderingdemo.com/category_images/3846.png" width="70" height="70" align="absmiddle" />
														</a>
													</td>
													
													<td valign="middle" width="75%" style="line-height:15px;">
														<a style="font-size:1em;" href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'WOOD-FIRE SIGNATURES')) ?>">WOOD-FIRE SIGNATURES</a></td>
												</tr>
											</table>
										</td>
									</tr>
									
									<tr>
										<td align="left" class="border_bottom3 menu_nagivation_rows">
											<table width="100%">
												<tr>
													<td valign="middle" width="25%">
														<a href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'SOUPS')) ?>">
														<img src="https://www.onlineorderingdemo.com/category_images/3843.png" width="70" height="70" align="absmiddle" /></a>
													</td>
													
													<td valign="middle" width="75%" style="line-height:15px;">
														<a style="font-size:1em;" href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'SOUPS')) ?>">SOUPS</a>
													</td>
												</tr>
											</table>
										</td>
									</tr>
									  
														   
									<tr>
										<td align="left" class="border_bottom3 menu_nagivation_rows">
											<table width="100%">
												<tr>
													<td valign="middle" width="25%">
														<a href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'PIZZA')) ?>">
														<img src="https://www.onlineorderingdemo.com/category_images/3852.png" width="70" height="70" align="absmiddle" /></a>
													</td>
												
													<td valign="middle" width="75%" style="line-height:15px;">
														<a style="font-size:1em;" href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'PIZZA')) ?>">PIZZA</a></td>
												</tr>
											</table>
										</td>
									</tr>
									
									<tr>
										<td align="left" class="border_bottom3 menu_nagivation_rows">
											<table width="100%">
												<tr>
													<td valign="middle" width="25%">
														<a href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'SANDWICHES')) ?>">
														<img src="https://www.onlineorderingdemo.com/category_images/3849.png" width="70" height="70" align="absmiddle" /></a>
													</td>
													
													<td valign="middle" width="75%" style="line-height:15px;">
														<a style="font-size:1em;" href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'SANDWICHES')) ?>">SANDWICHES</a>
													</td>
												</tr>
											</table>
										</td>
									</tr>
									
									<tr>
										<td align="left" class="border_bottom3 menu_nagivation_rows">
											<table width="100%">
												<tr>
													<td valign="middle" width="25%">
														<a href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'PASTA')) ?>">
															<img src="https://www.onlineorderingdemo.com/category_images/3848.png" width="70" height="70" align="absmiddle" />
														</a>
													</td>
													
													<td valign="middle" width="75%" style="line-height:15px;">
														<a style="font-size:1em;" href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'PASTA')) ?>">PASTA</a>
													</td>
												</tr>
											</table>
										</td>
									</tr>
														   
									<tr>
										<td align="left" class="border_bottom3 menu_nagivation_rows">
											<table width="100%">
												<tr>
													<td valign="middle" width="25%">
														<a href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'SEAFOOD')) ?>">
															<img src="https://www.onlineorderingdemo.com/category_images/3847.png" width="70" height="70" align="absmiddle" />
														</a>
													</td>
													
													<td valign="middle" width="75%" style="line-height:15px;">
														<a style="font-size:1em;" href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'SEAFOOD')) ?>">SEAFOOD</a>
													</td>
												</tr>
											</table>
										</td>
									</tr>
														   
									<tr>
										<td align="left" class="border_bottom3 menu_nagivation_rows">
											<table width="100%">
												<tr>
													<td valign="middle" width="25%">
														<a href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'SIDES')) ?>">
															<img src="https://www.onlineorderingdemo.com/category_images/3851.png" width="70" height="70" align="absmiddle" />
														</a>
													</td>
													
													<td valign="middle" width="75%" style="line-height:15px;">
														<a style="font-size:1em;" href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'SIDES')) ?>">SIDES</a>                                                </td>
												</tr>
											</table>
										</td>
									</tr>
									
									<tr>
										<td align="left" class="border_bottom3 menu_nagivation_rows">
											<table width="100%">
												<tr>
													<td valign="middle" width="25%">
														<a href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'DESSERTS')) ?>">
														<img src="https://www.onlineorderingdemo.com/category_images/3853.png" width="70" height="70" align="absmiddle" /></a>
													</td>
													
													<td valign="middle" width="75%" style="line-height:15px;">
														<a style="font-size:1em;" href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'DESSERTS')) ?>">DESSERTS</a>
													</td>
												</tr>
											</table>
										</td>
									</tr>
									
									<tr>
										<td align="left" class="border_bottom3 menu_nagivation_rows">
											<table width="100%">
												<tr>
													<td valign="middle" width="25%">
														<a href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'BEVERAGES')) ?>">
															<img src="https://www.onlineorderingdemo.com/category_images/3854.png" width="70" height="70" align="absmiddle" />
														</a>
													</td>
													
													<td valign="middle" width="75%" style="line-height:15px;">
														<a style="font-size:1em;" href="<?php echo $this->getUrl('restaurant/cmenu/show', array('id' => $this->getRequest()->getParam('id'), 'catid'=>'BEVERAGES')) ?>">BEVERAGES</a>
													</td>
												</tr>
											</table>
										</td>
									</tr>
									  
						</table>
					</div>
				  </td>
			  </tr>
			  
			</table>
								</td>
							 <td align="center" valign="top">  
					<table width="95%" border="0"  cellspacing="0" cellpadding="0">
						<tr>
							<td class="cu_inner_heading" align="left">
								<div style="line-height:36px;font-size:15px;">Fresh Local Bistro</div>
							</td>
						</tr>
						
						<?php
						$cat_id = $this->getRequest()->getParam("catid");
						if(isset($cat_id) && !empty($cat_id)) {
							$items = Mage::getModel("restaurant/item")->getCollection()
								->addFieldToFilter("restaurantmenu_id", $this->getRequest()->getParam('id'))
								->addFieldToFilter("category", $this->getRequest()->getParam('catid'));
							if($items->getSize() > 0) {
								foreach($items as $item) {
									?>
									<tr class="odd">
														<td  class="general_text menu_item" style="padding:3px; height:50px; width:100%;">
															<div class="menu_item_name">
																<a rel='example_group18003' href='item_images/3845/18003_1_default.jpg' title='Bruschetta & Grilled Garlic Crostini' onclick='return false' >
																	<img style='position:relative;z-index:10;' src="http://livetameion.com/media/restaurant_menu/<?php echo $item->getImage(); ?>" width='80' height='80' border='0' alt='' align='left' />
																</a>&nbsp;
																<a href="javascript:void(0)" onClick='reset_level(); create_categoryid_on_add(3845); get_pro_details("18003", "3845","Bruschetta & Grilled Garlic Crostini", "left"); openthickbox("18003","Bruschetta & Grilled Garlic Crostini");'>
																	<?php echo $item->getName(); ?>
																</a>
															</div>
															<div>
																<div class="menu_item_size" style="width:300px; word-wrap:break-word;">
																	<span>(Tapa&nbsp;4.49)</span>&nbsp;&nbsp;&nbsp;<span>(Appetizer&nbsp;6.99)</span>&nbsp;&nbsp;&nbsp;		
																</div>
																<div style="padding-bottom:5px;"></div>
																Fresh Tomato, Basil,Red Wine Vinaigrette, and Extra Virgin Olive Oil<br />
															</div>
														</td>
														<td colspan="3" align="right" valign="top" style="padding-top:3px; vertical-align:middle; padding-right: 5px;" class="menu_item_add">
															<input type="button" name="add_item" id="add_item" value="Add Item"
															class="myButton" style="height:38px;"															onclick='reset_level(); 
																create_categoryid_on_add(3845); 
																get_pro_details("18003","3845","Bruschetta & Grilled Garlic Crostini", "left"); 
																openthickbox("18003","Bruschetta & Grilled Garlic Crostini");' />
														</td>
													</tr>
									<?php
								} 
							} else {
								$this->__("No item available");
							}
						} else {
							?>
							<tr>
								<td colspan="2" align="left" bordercolor="#FFFFFF" class="">
									<table width="100%" border="0">
										<tr>
											<td width="70%" rowspan="4" class="cart_text_2">
												<br />
												<div><a href="get_map9a08.html?restaurant_id=385&amp;del_status=1" rel="ibox&width=1000&height=480" title="Map Details" ><div class="float_left icon_large map"><img src="https://www.onlineorderingdemo.com/css/images/icons/map.png"></div></a>
													<strong>Address:</strong><br>
														453 Lincoln St<br>Carlisle,&nbsp;PA&nbsp;17013<br><br>
													<span style="margin-left: 38px;">8777876368</span>
												</div>
											</td>
											<td align="right">
												<!--<div style="height:32px; line-height:32px;">
													<a href="javascript:void(0)" onClick="javaScript:window.open('email_to_friend.php','','width=520, height=390,scrollbars=NO')">
														Email to Friend												<div class="float_right icon_large email"></div>
													</a>
												</div><br />
												-->
												<div style="height:32px; line-height:32px;">
													<span class="st_sharethis_custom" style="cursor:pointer"><a>Share Menu</a></span>
													<div class="float_right icon_large sharethis"></div>
												</div><br />
												<div style="height:32px; line-height:32px;">
													<a href="javascript:void(0)" onClick="javaScript:window.open('menu_item_print.html','','width=600 ,height=800,scrollbars=1')">
														Print Menu												<div class="float_right icon_large print"></div>
													</a>
												</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" align="left" bordercolor="#FFFFFF" class="">
									<table width="50%" border="0">
										<tr>
											<td width="50%" rowspan="4" class="cart_text_2">
												<div class="ui-corner-all" style="border: 1px solid #b5b7b4; margin-top: 10px; display:block; position:relative; padding:15px;">
													<img src="https://www.onlineorderingdemo.com/css/images/icons/arrow.png" style="float: left; padding: 5px; vertical-align: middle;" />
													<strong>Choose a Menu Category to Begin Your Order</strong>
												</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" align="left">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="2" align="left">&nbsp;</td>
							</tr>
							<tr>
								<td align="center" id="errorMsgStr"></td>
							</tr>
							<tr>
								<td colspan="2" align="left" class="border_bottom2">
									<div class="float_left icon_small user"></div>
									<span>About Us</span>
								</td>
							</tr>
							<tr>
								<td colspan="2" align="left" class="cart_text_2">Our team at Fresh Local Bistro are committed to providing comfort food in a comfortable environment. All of our ingredients are grown locally and we offer a broad assortment of fair trade products from around the world. Support your local economy and stop by today!</td>
							</tr>
							<tr>
								<td colspan="2" align="left">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="2" align="left" class="border_bottom2">
									<div class="float_left icon_small info"></div>
									<span>Order Information</span>
								</td>
							</tr>
							<tr>
								<td colspan="2" align="left">
									<table width="100%"  border="0"> 
										<tr>
											<td width="12%" class="border_dotted cart_text_2">Notice for Pickup/Dine-In:</td>
											<td width="29%" class="border_dotted cart_text_2">
												<strong>
												15 mins										</strong>
											</td>
										</tr>
										<tr>
											<td width="12%" class="border_dotted cart_text_2">Notice for Delivery:</td>
											<td width="29%" class="border_dotted cart_text_2">
												<strong>
												30 mins										</strong>
											</td>
										</tr>
																									  
										<tr>
											<td width="12%" class="border_dotted cart_text_2">Min. Delivery Amount:</td>
											<td class="border_dotted cart_text_2"><strong>$10.00</strong></td>
										</tr>
										  
										<tr>
											<td width="12%" class="border_dotted cart_text_2">Delivery Zones & Fees:</td>
											<td class="border_dotted cart_text_2"><a href="get_map9a08.html?restaurant_id=385&amp;del_status=1" rel="ibox&width=1000&height=480" title="View" style="text-decoration:none"><b><u>View</u></b> <img src="https://www.onlineorderingdemo.com/images/info_icon.png" width="18" height="16"></a></td>
										</tr>
										
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2" align="left" valign="top">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="2" align="left" class="border_bottom2">
									<div class="float_left icon_small money"></div><span>Accepted Payments Online</span>
								</td>
							</tr>
							<tr>
								<td colspan="2" align="left" class="border_dotted">
									<img src="https://www.onlineorderingdemo.com/images/99.png" width="45" height="28" vspace="5" class="tTip" title="We accept Cash" /> 
									<img src="https://www.onlineorderingdemo.com/images/15.png" width="45" height="28" vspace="5" class="tTip" title="We accept Visa"/> 
									<img src="https://www.onlineorderingdemo.com/images/16.png" width="45" height="28" vspace="5" class="tTip" title="We accept MasterCard"/>
									<img src="https://www.onlineorderingdemo.com/images/17.png" width="45" height="28" vspace="5" class="tTip" title="We accept Discover"/> 
									<img src="https://www.onlineorderingdemo.com/images/18.png" width="45" height="28" vspace="5" class="tTip" title="We accept American Express"/>
									<span class="tTip" title="We accept House Account: 							Double click to add tooltip.										Please include your 14 digit house account number" ><img src="https://www.onlineorderingdemo.com/images/custompayment.png" width="45" height="28" vspace="5" /><b style="vertical-align: 15px;">House Account</b></span>&nbsp;
								</td>
							</tr>          
							<!-- View working time -->			
							<tr>
								<td colspan="2" align="left">		
									<div align="left">
										<table border="0" align="left" cellpadding="2" cellspacing="0" width="100%" class="">
											<tr>
												<td colspan="3" align="left" class="border_bottom2">
													<div class="float_left icon_small clock"></div><span>Store Hours</span>
												</td>
											</tr>
											<tr id="MONDAY">
												<td align="left" class="cart_text_2" style="display:block;">
													<strong>MONDAY</strong></td>
												<td>&nbsp;</td>
											
												<td class="cart_text_2">10:00 AM - 3:00 PM</td>		
																					</tr>
											<tr id="TUESDAY">
												<td align="left" class="cart_text_2" style="display:block;">
													<strong>TUESDAY</strong></td>
												<td>&nbsp;</td>
												
												<td class="cart_text_2">10:00 AM - 3:00 PM</td>		
											</tr>
											<tr id="WEDNESDAY">
												<td align="left" class="cart_text_2" style="display:block;">
													<strong>WEDNESDAY</strong></td>
												<td>&nbsp;</td>
											
												<td class="cart_text_2">10:00 AM - 3:00 PM</td>		
											</tr>
											<tr id="THURSDAY">
												<td align="left" class="cart_text_2" style="display:block;">
													<strong>THURSDAY</strong>
												</td>
												<td>&nbsp;</td>
													
												<td class="cart_text_2">10:00 AM - 3:00 PM</td>		
											</tr>
											<tr id="FRIDAY">
												<td align="left" class="cart_text_2" style="display:block;">
													<strong>FRIDAY</strong>
												</td>
												<td>&nbsp;</td>
												
												<td class="cart_text_2">10:00 AM - 6:00 PM</td>		
											</tr>
											<tr id="SATURDAY">
												<td align="left" class="cart_text_2" style="display:block;">
													<strong>SATURDAY</strong></td>
												<td>&nbsp;</td>
												
												<td class="cart_text_2">10:00 AM - 6:00 PM</td>		
											</tr>
											<tr id="SUNDAY">
												<td align="left" class="cart_text_2" style="display:block;">
													<strong>SUNDAY</strong></td>
												<td>&nbsp;</td>
												<td class="cart_text_2">10:00 AM - 3:00 PM</td>		
											</tr>
										</table>
									</div>
								</td>
							</tr>
							<!-- End view working time -->
							<?php 
						} ?>
						
						<tr>
							<td colspan="2" align="left" valign="top">&nbsp;</td>
						</tr>
												<tr>
							<td colspan="2" align="left" valign="top">&nbsp;</td>
						</tr>
					</table>
				  </td>			 <td width="200" align="center" valign="top" style="padding-right:10px;">
	<!-- added by Kryz for toggling online ordering -->
	<!-- Link to the stylesheet -->
	<link rel="stylesheet" type="text/css" href="css/ui-lightness/jquery-ui-1.8.10.custom.css" />
	<style type="text/css">
	.addon_hover:hover
	{
		background-color: #c9c5c9;
	}
	</style>

	<script type="text/javaScript">var restaurantID = 385</script><script type='text/javaScript'>var locationId = 359</script><script type='text/javaScript'>var inFacebook = 0</script><script type="text/javascript">

	function chkamount1(minamount)
	{
		$.ajax({
			url: "../get_cart_total.php",
			type: 'GET',
			dataType: 'json',
			success: function(data) 
			{
				//alert('ajax result ' + data);
				var cart_total = data;
				//alert('cart_total ' + cart_total);
				if( cart_total < minamount )
				{
					alert('Your subtotal is less than the Minimum Delivery amount which is noted on our home page. Please shop some more to continue with Delivery.');
					return(false);
				}
				else
				{
					//alert('throw ok');
					window.location.href="index.html?type=delivery";
				}
			},
			error: function(e, xhr, setting, exception)
			{
				alert(e + '   ' + xhr + '   ' + setting + '   ' + exception );
			}
		});

	return(false);

	}
	</script>

	<table id="toggle_online_orders" width="200" border="0" align="center" cellpadding="0" cellspacing="0" >
		<tr>
			<td class="cart_side_heading">
				<a href="viewcart14c8.html?a=view" style="color:white;">MY ORDER</a>
			</td>
		</tr>


		 <tr>
			<td align="center">
				<table id="cart_container" width="100%" border="0" cellspacing="0" cellpadding="2">                  
					<tr class="cart_fill_1 cart_text_1">
						<td align="left" width="70%" class="cart_border_left cart_border_bottom cart_text_1">ITEM</td>
						<td align="left" class="cart_border_bottom cart_text_1">QTY</td>
						<td  align="right" width="30%" class="cart_border_right cart_border_bottom cart_text_1">PRICE</td>
					</tr>
					<tr>
						<td class="cart_text_2 cart_fill_2 cart_border_left cart_border_right" colspan="3" align="right" style="font-weight:bold;"> Subtotal: $0.00</td>
					</tr>
				
			<tr>
				<td height="8" colspan="3" class="cart_border_left cart_border_right cart_border_top cart_fill_1"></td>
			</tr>

			<tr>
				<td  align="center" class="cart_border_left cart_fill_1">

			
				</td>
				<td align="center" class="cart_border_right cart_fill_1" colspan="2">
							
						</td>
					</tr>
					<tr ><td colspan="3" class="cart_border_left cart_border_right cart_border_bottom cart_fill_1 cart_text_1" style="padding-left:22px;padding-top:10px;padding-bottom:10px;">
									<img src="images/grouporder_white.png" width="19" height="15" border="0" />
										<a href="javascript:void(0);" class="login" >
											<span class="cart_text_1" style="font-weight:bold;text-decoration:underline;">
												Start a Group Order
											</span>
										</a>
									</td></tr>                <tr>
						<td colspan="3" style="padding-left:25px;" class="cart_border_left cart_border_right cart_border_bottom cart_fill_1 cart_text_1">
							<span id="order_type_cart"></span>
							<span id="change_order_type_cart" style="font-size:10px;">
							
								<a onclick="showOrderType(0)" href="javascript:void(0)">
									<span class="cart_text_1">
										Choose Order Type
									</span>
								</a>        				</span>
						</td>
					</tr>
									</table>
			</td>
		</tr>
		<tr>
			<td align="left"  class="cart_bottom">&nbsp;
				
			</td>
		</tr>
	</table>
	<br />
		
			<table width="185" border="0" align="center" cellpadding="0" cellspacing="0">
				<!--Removed this for aesthetic reasons
							-->
				
						</table>
	<div id="Layer" style="display:none;">

	<!--
	<div style="text-align:right; padding-right:5px; padding-bottom:5px;">testing
		<input "style="cursor:pointer" 
		class="checkout_close button_cancel"	type="button" value="Go Back" />
	</div>
	-->
	</div>
	</div>
	<br/>
	<div id="upsell_item" title="Add to your Meal"></div>
	<div id="order_type" title="Order Type"></div>
	<div id="get_hours" title="Store Hours"></div>

	<script type="text/javascript">
	var order_type_alert = 0 
	var order_type_alert_required = 0</script>
	<script type="text/javaScript" src="javascript/shopping_cartdbf6.js?version=041415"></script>
	<script type="text/javaScript" src="javascript/shopping_cart2dbf6.js?version=041415"></script>
	<script type="text/javaScript" src="javascript/group_orderdbf6.js?version=041415"></script>
	  <table  border="0" cellpadding="0" cellspacing="0" width="200" height="300">
		<tr style="margin:0px; padding:0px;">
			<td valign="top" align="center" colspan="10" width="">
									<a id="coupon_ad" href="https://www.facebook.com/freshlocalbistro" target="_blank""><img src="coupon_ads/359.png" border="0" /></a>
							</td>
		</tr>
		<!--
		<tr>
			<td></td>
		</tr>
		-->
	  </table>
					<br />
					
				 </td>
			  </tr>
			</table>
			</td>
		  </tr>
		  <tr>
			<td align="center">
				<div class="border_bottom_body"><style></style>      <link rel="stylesheet" type="text/css" href="css/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
		  <script type="text/javascript" src="javascript/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
		  <script type="text/javascript" src="javascript/fancybox/jquery.fancybox-1.3.4.js"></script>
		  <script type="text/javascript" src="javascript/fancybox/fancy.js"></script>
		  
		  <div style="padding-top:5px;"><div>
			<table width="95%"  border="0" class="footer">
			  <tr>
				<td id="" align="left" style="font-size: 10px; padding-top:5px;">
					<a href="terms.html"><b>Terms of Use</b></a> | 
					<a href="privacypolicy.html"><b>Privacy Policy</b></a> |
					<a href="http://menuordering.wufoo.com/forms/z7x3p3/" onclick="window.open(this.href,  null, 'height=747, width=680, toolbar=0, location=0, status=1, scrollbars=1, resizable=1'); return false"><b>Tech Support</b></a>
				</td>
			  </tr>
			  <tr>
				<td>
					<table width="100%" border="0">
						<tr>
							<td width="80%" style="text-align:right;padding-right:15px;"><br /><img src="images/godaddy_seal.png" /></td>
													<td style="padding-right:15px;"><a href="http://www.menudrive.com/receipt-powered-logo" target="_blank"><img src="images/powered_menudrive.png" border="0" /></a></td>
													<td>
												   </td>
						</tr>
					</table>
				</td>
			  </tr>
	  </table>

			



	<!-- Disabled Statcounter because the https was not loading and causing conflicts (Adrian)-->
	<!-- Start of StatCounter Code -->
	<!--<script type="text/javascript">
	var sc_project=5859605; 
	var sc_invisible=1; 
	var sc_security="7ac886c3"; 
	</script>

	<script type="text/javascript"
	src="https://www.statcounter.com/counter/counter.js"></script><noscript><div
	class="statcounter"><a title="create counter"
	href="https://www.statcounter.com/free_hit_counter.html"
	target="_blank"><img class="statcounter"
	src="https://c.statcounter.com/5859605/0/7ac886c3/1/"
	alt="create counter" ></a></div></noscript> -->
	<!-- End of StatCounter Code -->

	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-16340249-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>
	</div>
		   </td>
		  </tr>
		</table>
		
		<!-- This is called from restaurant_home.php -> javascript/restaurant_home.js which loads the dialog box from message.html-->
		<div id="disable_online_orders"></div>
		<div id="signup" title="New Account Registration"></div>
		<div style="padding: 25px;"></div>	
		</body>
		
	<!-- Mirrored from www.onlineorderingdemo.com/freshlocalbistro by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 14 Apr 2015 12:05:37 GMT -->
	</html>
<?php } ?>
