<div class="page-title">
	<h1><?php echo $this->__('Restaurant Menu - Edit') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/update') ?>" method="post" id="form-validate-restaurant" enctype="multipart/form-data">
	<div class="fieldset">
		<?php echo $this->getBlockHtml('formkey') ?>
		<input type='hidden' name='restaurantmenu_id' value='<?php echo $this->getRequest()->getParam('id'); ?>' />
			<h2 class="legend"><?php echo $this->__('Restaurant Menu Information') ?></h2>
			<ul class="form-list">
			<li>
				<div class="field">
					<label for="stores" class="required"><em>*</em><?php echo $this->__('Store') ?></label>
					<div class="input-box">
						<?php
						$adDetails = Mage::getModel('restaurant/menu')->load($this->getRequest()->getParam('id'))->getData();
						$Stores=array();
						$storeCollection=Mage::getModel('core/store_group')->getCollection();
						foreach($storeCollection as $store) {
							$storelang= Mage::getStoreConfig('general/locale/code', $store->getId());
							$Stores[]=$store->getData();
						}						
						?>
						<select name="stores" id="stores" class="required-entry select" onchange="callController(this.value);">
							<option value="" selected="selected"><?php echo $this->__('Please Select Store--'); ?></option>
							<?php 
							foreach($Stores as $eachstore) {
								if($eachstore['default_store_id'] == $adDetails['store_id']) {
									?>
									<option selected value="<?php echo $eachstore['default_store_id']; ?>"><?php echo $eachstore['name']; ?></option>
									<?php
								} else {
									?>
									<option value="<?php echo $eachstore['default_store_id']; ?>"><?php echo $eachstore['name']; ?></option>
									<?php
								}
							}	 
							?> 
							<?php				
							/*$allStores  = Mage::helper('restaurant')->getAllstoreColletion();
							
							foreach ($allStores as $_eachStoreId => $val) 
							{
								$_storeCode = Mage::app()->getStore($_eachStoreId)->getCode();
								$_storeName = Mage::app()->getStore($_eachStoreId)->getName();
								$_storeId = Mage::app()->getStore($_eachStoreId)->getId();
								?>
								<option value="<?php echo $_storeId; ?>"><?php echo $_storeName; ?></option>
							<?php					
							}*/
							?>
						</select>
					</div>
				</div>
			</li>
			
            <li>
				<div class="field">
					<label for="category" class="required"><em>*</em><?php echo $this->__('Product Category') ?></label>
					<div class="input-box" id="category_html"><?php echo getCategoriesFor($adDetails['store_id']); ?></div>
				</div>
			</li>
			
			<li>
				<div class="field">
					<div class="upload-head">
						<label for="image" class="required"><?php echo $this->__('Upload Image') ?></label>
					</div>
					<div class="input-box">
						<input type="file" id="restaurantmenu-image" name="restaurantmenu-image"  title="<?php echo $this->__('Image') ?>" class="input-text required-entry" />
					</div>
				</div>
			</li>
			<?php
			$page_locations = array(
				array('key'=>'right', 'val'=>'Right'),
				array('key'=>'bottom', 'val'=>'Bottom')
			);
			?>
			<li>
				<div class="field">
					<div class="upload-head">
						<label for="image" class="required"><?php echo $this->__('Page Location') ?></label>
					</div>
					<select name="page_location" id="page_location" class="required-entry select">;
						<?php
						foreach($page_locations as $loc) {
							if($loc['key'] == $adDetails['page_location']) {
								?>
								<option selected value="<?php echo $loc['key']; ?>"><?php echo $loc['val']; ?></option>
								<?php
							} else {
								?>
								<option value="<?php echo $loc['key']; ?>"><?php echo $loc['val']; ?></option>
								<?php
							}
						}
						?>
					</select>
				</div>
			</li>
			
                <li>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link">
            <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>">
                <small>&laquo; </small>
                <?php echo $this->__('Back') ?>
            </a>
        </p>
        <button type="submit" title="<?php echo $this->__('Update') ?>" class="button"><span><span><?php echo $this->__('Update') ?></span></span></button>
    </div>
</form>

<?php

function getCategoriesFor($store_id) {
	if($store_id) {
		$html_ .='<select name="category_ids[]" id="category" class="required-entry select multiselect" multiple="multiple">';	
			$category=Mage::getModel('catalog/category')
			->getCollection()
			->setStoreId($store_id)
			->setOrder('position', 'asc')
			->addFieldToFilter('is_active', array('eq'=>'1'))
			->addAttributeToSelect('*');
			
		foreach ($category as $cat) {
			$html_ .='<option value="'.$cat->getId().'">'.$cat->getName().'</option>';
		}
		$html_ .='</select>';
		return $html_ ;
	} else {
		return '';
	}
}
?>

<script type="text/javascript">
//<![CDATA[
var productForm = new VarienForm('form-validate-restaurant', true);
//]]>
function callController(sid) {
	new Ajax.Request("<?php echo $this->getUrl('restaurant/index/gettoreategory') ?>", {
		method: 'Post',
		parameters: {'store_id':sid},
		onComplete: function(transport) {
			document.getElementById('category_html').innerHTML=transport.responseText;
			//alert(transport.responseText);
		}
	});
}
</script>