<div class="page-title">
	<h1><?php echo $this->__('Menu Item - Add') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/item/save') ?>" method="post" id="form-validate-restaurant" enctype="multipart/form-data">
	<div class="fieldset">
		<?php echo $this->getBlockHtml('formkey') ?>
		<h2 class="legend"><?php echo $this->__('Menu Item Information') ?></h2>
		<input type='hidden' name='menu_id' value='<?php echo $this->getRequest()->getParam('menuid'); ?>' />
		<?php echo $this->getChildHtml("fieldset"); ?>
	</div>
</form>

<script type="text/javascript">
//<![CDATA[
var productForm = new VarienForm('form-validate-restaurant', true);
//]]>
function callController(sid) {
	new Ajax.Request("<?php echo $this->getUrl('restaurant/index/gettoreategory') ?>", {
		method: 'Post',
		parameters: {'store_id':sid},
		onComplete: function(transport) {
			document.getElementById('category_html').innerHTML=transport.responseText;
			alert(transport.responseText);
			//alert(sid);
		}
	});
}

function add_item_fields() {
	
	var new_item_html = "<div class='menu_item'>" +
				"<span class='delete_menu_item' onClick=\"delete_menu_item(this)\">X</span>" +
				"<li>" +
					"<div class=\"field\">" +
						"<label for=\"stores\" class=\"required\"><em>*</em>Item Name</label>" +
						"<div class=\"input-box\">" +
							"<input type='text' name='item_name[]' class='input-text required-entry' />" +
						"</div>" +
					"</div>" +
				"</li>" +
				
				"<li>" +
					"<div class=\"field\">" +
						"<label for=\"stores\" class=\"required\"><em>*</em>Price</label>" +
						"<div class=\"input-box\">" +
							"<input type='text' name='item_price[]' class='input-text required-entry' />" +
						"</div>" +
					"</div>" +
				"</li>" +
				
				"<li>" +
					"<div class=\"field\">" +
						"<label for=\"category\" class=\"required\"><em>*</em>Category</label>" +
						"<div class=\"input-box\">" +
							"<select name='category[]' class='input-text required-entry'>" +
								"<option>APPETIZERS & TAPAS</option>" +
								"<option>WOOD-FIRE SIGNATURES</option>" +
								"<option>SOUPS</option>" +
								"<option>PIZZA</option>" +
								"<option>SANDWICHES</option>" +
								"<option>PASTA</option>" +
								"<option>SEAFOOD</option>" +
								"<option>SIDES</option>" +
								"<option>DESSERTS</option>" +
								"<option>BEVERAGES</option>" +
							"</select>" +
						"</div>" +
					"</div>" +	
				"</li>" +
				
				"<li>" +
					"<div class=\"field\">" +
						"<div class=\"upload-head\">" +
							"<label for=\"image\" class=\"required\"></label>" +
						"</div>" +
						"<div class=\"input-box\">" +
							"<input type=\"file\" id=\"item_image\" name=\"item_image[]\"  title=\"Image\" class=\"input-text required-entry\" />" +
						"</div>" +
					"</div>" +
				"</li>" +
			"</div>";
	
	var li = document.createElement("li");
	li.innerHTML = 'dfdfdfdfdfdfdfdfdf';
	document.getElementById('menu_item_form_fields').innerHTML += new_item_html;
}

function delete_menu_item(node) {
	node.parentNode.remove();
}
</script>