<style>
.menu_item {
	border:1px solid grey;
	padding:5px;
	margin-bottom:5px;
}

.delete_menu_item {
	float:right;
	cursor:pointer;
}
</style>
<?php
$actionName = Mage::app()->getRequest()->getActionName();
$id = Mage::app()->getRequest()->getParam("id");
$edit_mode = (($actionName == "edit") && isset($id) && !empty($id));
global $item;
$item = Mage::getModel('restaurant/item')->load($id);
if( $edit_mode ) {
	$name = $item->getName();
	$description = $item->getDescription();
	$size = $item->getSize();
	$categoryy = $item->getCategoryIds();
	//$name = $item->getName();
}
?>
<ul class="form-list" id='menu_item_form_fields'>
	<div class='menu_item'>
		<span class='delete_menu_item' onClick="delete_menu_item(this)">X</span>
		<li>
			<div class="field">
				<label for="stores" class="required"><em>*</em><?php echo $this->__('Item Name') ?></label>
				<div class="input-box">
					<input type='text' name='item_name[]' class='input-text required-entry' value="<?php echo $name; ?>" />
				</div>
			</div>
		</li>
			
		<li>
			<div class="field">
				<label for="stores" class="required"><em>*</em><?php echo $this->__('Description') ?></label>
				<div class="input-box">
					<textarea name='description[]' class='input-text required-entry'><?php echo $description; ?></textarea>
				</div>
			</div>
		</li>
		
		<li>
			<div class="field">
				<label for="stores" class="required"><em>*</em><?php echo $this->__('') ?></label>
				<div class="radio">
					<input type='radio' name='size[0]' class='radio single_size required-entry' value='<?php echo Livetameion_Restaurant_Model_Item::SINGLE_SIZE; ?>' <?php echo ($size == Livetameion_Restaurant_Model_Item::SINGLE_SIZE) ? 'checked':'' ?> /> Single Size
				</div>
			</div>
			<div class='single_size_fields'><?php if( $edit_mode && $size == Livetameion_Restaurant_Model_Item::SINGLE_SIZE ) { echo getSingleSizeFields(); } ?></div>
		</li>
		
		<li>
			<div class="field">
				<label for="stores" class="required"><em>*</em><?php echo $this->__('') ?></label>
				<div class="radio">
					<input type='radio' name='size[0]' class='radio multiple_size required-entry' value='<?php echo Livetameion_Restaurant_Model_Item::MULTIPLE_SIZE; ?>' <?php echo ($size == Livetameion_Restaurant_Model_Item::MULTIPLE_SIZE) ? 'checked':'' ?> /> Multiple Sizes
				</div>
			</div>
			<div class='multiple_size_fields'><?php if( $edit_mode && $size == Livetameion_Restaurant_Model_Item::MULTIPLE_SIZE ) { echo getMultipleSizeFields(); } ?></div>
		</li>
		
		<li>
			<div class="field">
				<label for="category" class="required"><em>*</em><?php echo $this->__('Category') ?></label>
				<div class="input-box">
					<select name='category[]' class='input-text required-entry'>
						<?php
						$categories = Mage::helper("restaurant")->getActiveCategories();
						foreach($categories as $category) {
							$category = Mage::getModel('restaurant/category')->load($category->getEntityId());
							if( edit_mode && ($category->getEntityId() == $categoryy) ) {
								$selected = "selected";
							} else {
								$selected = "";
							}
							?>
							<option value='<?php echo $this->__($category->getEntityId()) ?>' <?php echo $selected; ?> ><?php echo $this->__($category->getName()) ?></option>
							<?php
						}
						?>
					</select>
				</div>
			</div>			
		</li>
		
		<li>
			<div class="field">
				<div class="upload-head">
					<label for="image" class="required"><?php echo $this->__('Upload Image') ?></label>
				</div>
				<div class="input-box">
					<input type="file" id="item_image" name='item_image[]' title="<?php echo $this->__('Image') ?>" class="input-text required-entry" />
				</div>
			</div>
		</li>
	</div>
</ul>

<?php $actionName = Mage::app()->getRequest()->getActionName() ?>
<?php if( $actionName == "add" ) { ?>
	<div class="buttons-set">
		<p class="back-link">
			<a href="javascript:void(0)" id='add_new_item'>
				<?php echo $this->__('Add New Item') ?>
			</a>
		</p>
	</div>
<?php } ?>
<div class="buttons-set">
	<p class="required"><?php echo $this->__('* Required Fields') ?></p>
	<p class="back-link">
		<a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" >
			<small>&laquo; </small>
			<?php echo $this->__('Back') ?>
		</a>
	</p>
	<button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
</div>

<?php

function getSingleSizeFields() {
	global $item;
	$single_size_fields = "" .
		"<div class=\"field\">" .
			"<label for=\"stores\" class=\"required\"><em>*</em>Price</label>" .
			"<div class=\"input-box\">" .
				"<input type=\"text\" name=\"single_size_price[]\" class=\"input-text required-entry\" value=\"" . $item->getSingleSizePrice() . "\" />" .
			"</div>" .
		"</div>" .
	"";
	return $single_size_fields;
}

function getMultipleSizeFields() {
	global $item;
	$multiple_size_fields = "<li>" .
		"<div class=\"field\">" .
			"<label for=\"stores\" class=\"required\"><em>*</em>Small Size Price</label>" .
			"<div class=\"input-box\">" .
				"<input type=\"text\" name=\"small_size_price[]\" class=\"input-text required-entry\" value=\"" .  $item->getSmallSizePrice() . "\" />" .
			"</div>" .
		"</div>" .
		"<div class=\"field\">" .
			"<label for=\"stores\" class=\"required\"><em>*</em>Medium Size Price</label>" .
			"<div class=\"input-box\">" .
				"<input type=\"text\" name=\"medium_size_price[]\" class=\"input-text required-entry\" value=\"" .  $item->getMediumSizePrice() . "\" />" .
			"</div>" .
		"</div>" .
		"<div class=\"field\">" .
			"<label for=\"stores\" class=\"required\"><em>*</em>Large Size Price</label>" .
			"<div class=\"input-box\">" .
				"<input type=\"text\" name=\"large_size_price[]\" class=\"input-text required-entry\" value=\"" .  $item->getLargeSizePrice() . "\" />" .
			"</div>" .
		"</div>" .
		"<div class=\"field\">" .
			"<label for=\"stores\" class=\"required\"><em>*</em>Half Order Price</label>" .
			"<div class=\"input-box\">" .
				"<input type=\"text\" name=\"half_order_price[]\" class=\"input-text required-entry\" value=\"" . $item->getHalfOrderPrice() . "\" />" .
			"</div>" .
		"</div>" .
		"<div class=\"field\">" .
			"<label for=\"stores\" class=\"required\"><em>*</em>Full Order Price</label>" .
			"<div class=\"input-box\">" .
				"<input type=\"text\" name=\"full_order_price[]\" class=\"input-text required-entry\" value=\"" . $item->getFullOrderPrice() . "\" />" .
			"</div>" .
		"</div>" .
		"<div class=\"field\">" .
			"<label for=\"stores\" class=\"required\"><em>*</em>Child Size Price</label>" .
			"<div class=\"input-box\">" .
				"<input type=\"text\" name=\"child_order_price[]\" class=\"input-text required-entry\" value=\"" . $item->getChildOrderPrice() . "\" />" .
			"</div>" .
		"</div>" .
	"</li>";
	return $multiple_size_fields;
}
?>
<input type='hidden' id='single_size_fields_hidden' value='<?php echo getSingleSizeFields(); ?>' />
<input type='hidden' id='multiple_size_fields_hidden' value='<?php echo getMultipleSizeFields(); ?>' />

<?php
function getItemFields() {
	$categories = Mage::helper("restaurant")->getActiveCategories();
	$options = "";
	foreach($categories as $category) {
		$category = Mage::getModel('restaurant/category')->load($category->getEntityId());
		if( edit_mode && ($category->getEntityId() == $categoryy) ) {
			$selected = "selected";
		} else {
			$selected = "";
		}
		$options .= "<option value=\"" . $category->getEntityId() . "\" $selected>" . $category->getName() . "</option>";
	}
	
	$item_fields = "<span class=\"delete_menu_item\" onClick=\"delete_menu_item(this)\">X</span>" .
		"<li>" .
			"<div class=\"field\">" .
				"<label for=\"stores\" class=\"required\"><em>*</em>Item Name</label>" .
				"<div class=\"input-box\">" .
					"<input type=\"text\" name=\"item_name[]\" class=\"input-text required-entry\" value=\"" . $name . "\" />" .
				"</div>" .
			"</div>" .
		"</li>" .
		
		"<li>" .
			"<div class=\"field\">" .
				"<label for=\"stores\" class=\"required\"><em>*</em>Description</label>" .
				"<div class=\"input-box\">" .
					"<textarea name=\"description[]\" class=\"input-text required-entry\">" . $description . "</textarea>" .
				"</div>" .
			"</div>" .
		"</li>" .
		
		"<li>" .
			"<div class=\"field\">" .
				"<label for=\"stores\" class=\"required\"><em>*</em></label>" .
				"<div class=\"radio\">" .
					"<input type=\"radio\" name=\"size[1]\" class=\"radio single_size required-entry\" value=\"" . Livetameion_Restaurant_Model_Item::SINGLE_SIZE . "\" " . (($size == Livetameion_Restaurant_Model_Item::SINGLE_SIZE) ? "checked" : "") . " />Single Size" .
				"</div>" .
			"</div>" .
			"<div class=\"single_size_fields\"></div>" .
		"</li>" .
		
		"<li>" .
			"<div class=\"field\">" .
				"<label for=\"stores\" class=\"required\"><em>*</em></label>" .
				"<div class=\"radio\">" .
					"<input type=\"radio\" name=\"size[1]\" class=\"radio multiple_size required-entry\" value=\"" .  Livetameion_Restaurant_Model_Item::MULTIPLE_SIZE . "\" " . (($size == Livetameion_Restaurant_Model_Item::MULTIPLE_SIZE) ? "checked" : "") . " />Multiple Sizes" .
				"</div>" .
			"</div>" .
			"<div class=\"multiple_size_fields\"></div>" .
		"</li>" .
		
		"<li>" .
			"<div class=\"field\">" .
				"<label for=\"category\" class=\"required\"><em>*</em>Category</label>" .
				"<div class=\"input-box\">" .
					"<select name=\"category[]\" class=\"input-text required-entry\">" . $options . "</select>" .
				"</div>" .
			"</div>" .
		"</li>" .
		
		"<li>" .
			"<div class=\"field\">" .
				"<div class=\"upload-head\">" .
					"<label for=\"image\" class=\"required\">Upload Image</label>" .
				"</div>" .
				"<div class=\"input-box\">" .
					"<input type=\"file\" id=\"item_image\" name=\"item_image[]\" title=\"Image\" class=\"input-text required-entry\" />" .
				"</div>" .
			"</div>" .
		"</li>";
	
	return $item_fields;
}
?>
<input type='hidden' id='item_fields_hidden' value='<?php echo getItemFields(); ?>' />

<script type="text/javascript">
//<![CDATA[
var productForm = new VarienForm('form-validate-restaurant', true);
//]]>
function callController(sid) {
	new Ajax.Request("<?php echo $this->getUrl('restaurant/index/gettoreategory') ?>", {
		method: 'Post',
		parameters: {'store_id':sid},
		onComplete: function(transport) {
			document.getElementById('category_html').innerHTML=transport.responseText;
			alert(transport.responseText);
			//alert(sid);
		}
	});
}

function delete_menu_item(node) {
	node.parentNode.remove();
}
</script>

<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.11.2.min.js"></script>
<script>
$(function() {
	var size_radio_counter = 1;
	$("#menu_item_form_fields").on("click", ".single_size", function() {
		
		if( $(this).parents("li").next("li").find(".multiple_size_fields").children().length > 0 ) {
			$(this).parents("li").next("li").find(".multiple_size_fields").html("");
		}
		
		//alert($(this).parents("li").find(".single_size_fields").children().length);
		if ( $(this).is(":checked") && $(this).parents("li").find(".single_size_fields").children().length == 0 ) {
			var div = document.createElement("div");
			div.className = "size_item";
			div.innerHTML = document.getElementById('single_size_fields_hidden').value;
			$(this).parents("li").find(".single_size_fields").html(div);
		}
		
	});
	
	$("#menu_item_form_fields").on("click", ".multiple_size", function() {
		//alert($(this).parents("li").prev("li").find(".single_size_fields").children().length);
		
		if( $(this).parents("li").prev("li").find(".single_size_fields").children().length > 0 ) {
			$(this).parents("li").prev("li").find(".single_size_fields").html("");
		}
		
		//alert($(this).parents("li").find(".multiple_size_fields").children().length);
		if ( $(this).is(":checked") && $(this).parents("li").find(".multiple_size_fields").children().length == 0 ) {
			var div = document.createElement("div");
			div.className = "size_item";
			div.innerHTML = document.getElementById('multiple_size_fields_hidden').value;
			$(this).parents("li").find(".multiple_size_fields").html(div);
		}
	});
	
	$("#add_new_item").on("click", function() {
		var div = document.createElement("div");
		div.className = "menu_item";
		div.innerHTML = document.getElementById('item_fields_hidden').value;
		$(div).find(".single_size").attr("name", "size[" + size_radio_counter + "]");
		$(div).find(".multiple_size").attr("name", "size[" + size_radio_counter++ + "]");
		$("#menu_item_form_fields").append(div);
	});
});
</script>
